create or replace PROCEDURE CAPRA_LKP_INT_TRND_RPT
AS

V_TOTAL_PAID_AMT            NUMBER(20,4);
V_TOTAL_PAID_AMT1           NUMBER(20,4);
V_INTF_ID                   CAPRA_PAID_TXN_INTF_TRND.interface_id%TYPE ;
V_INTF_NM                   CAPRA_PAID_TXN_INTF_TRND.interface_nm%TYPE ;
V_SET_ID                    CAPRA_PAID_TXN_INTF_TRND.VDR_SET_ID%TYPE ;
V_PMT_MONTH                 CAPRA_PAID_TXN_INTF_TRND.pmt_month%TYPE;
V_PMT_YEAR                  CAPRA_PAID_TXN_INTF_TRND.pmt_year%TYPE;
V_WADT_AMT                  NUMBER(20,4);
V_PREV_YEAR                 NUMBER                              :=  EXTRACT(YEAR FROM SYSDATE)-1;
V_CURRENT_YEAR              NUMBER                              :=  EXTRACT(YEAR FROM SYSDATE);
V_PREV_TO_PREV_YEAR         NUMBER                              :=  EXTRACT(YEAR FROM SYSDATE)-2;
V_CURRENT_MONTH             NUMBER                              :=  EXTRACT(MONTH FROM SYSDATE);
V_CURR_YR_PDAMT             NUMBER(20,4);
V_PREV_YR_PDAMT             NUMBER(20,4);
V_PREV_TO_PREV_YR_PDAMT     NUMBER(20,4);


V_PERCENT_INCR_PREV_MONTH   NUMBER(8,1);
V_PERCENT_INCR_JAN2015      NUMBER(8,1);
V_PERCENT_INCR_JAN2016      NUMBER(8,1);
V_DTP_VAL1                  NUMBER(6,1);
V_DTP_VAL2                  NUMBER(6,1);

V_JAN_2015_WADTP            NUMBER(20,4);
V_FEB_2015_WADTP            NUMBER(20,4);
V_MAR_2015_WADTP            NUMBER(20,4);
V_APR_2015_WADTP            NUMBER(20,4);
V_MAY_2015_WADTP            NUMBER(20,4);
V_JUN_2015_WADTP            NUMBER(20,4);
V_JUL_2015_WADTP            NUMBER(20,4);
V_AUG_2015_WADTP            NUMBER(20,4);
V_SEP_2015_WADTP            NUMBER(20,4);
V_OCT_2015_WADTP            NUMBER(20,4);
V_NOV_2015_WADTP            NUMBER(20,4);
V_DEC_2015_WADTP            NUMBER(20,4);

V_JAN_2016_WADTP            NUMBER(20,4);
V_FEB_2016_WADTP            NUMBER(20,4);
V_MAR_2016_WADTP            NUMBER(20,4);
V_APR_2016_WADTP            NUMBER(20,4);
V_MAY_2016_WADTP            NUMBER(20,4);
V_JUN_2016_WADTP            NUMBER(20,4);
V_JUL_2016_WADTP            NUMBER(20,4);
V_AUG_2016_WADTP            NUMBER(20,4);
V_SEP_2016_WADTP            NUMBER(20,4);
V_OCT_2016_WADTP            NUMBER(20,4);
V_NOV_2016_WADTP            NUMBER(20,4);
V_DEC_2016_WADTP            NUMBER(20,4);

V_JAN_2017_WADTP            NUMBER(20,4);
V_FEB_2017_WADTP            NUMBER(20,4);
V_MAR_2017_WADTP            NUMBER(20,4);
V_APR_2017_WADTP            NUMBER(20,4);
V_MAY_2017_WADTP            NUMBER(20,4);
V_JUN_2017_WADTP            NUMBER(20,4);
V_JUL_2017_WADTP            NUMBER(20,4);
V_AUG_2017_WADTP            NUMBER(20,4);
V_SEP_2017_WADTP            NUMBER(20,4);
V_OCT_2017_WADTP            NUMBER(20,4);
V_NOV_2017_WADTP            NUMBER(20,4);
V_DEC_2017_WADTP            NUMBER(20,4);
     
CURSOR C_MAIN
IS
SELECT DISTINCT INTERFACE_ID 
FROM CAPRA_PAID_TXN_INTF_TRND WHERE INTERFACE_ID IS NOT NULL; -- AND INTERFACE_ID IN ('3PP','13966');

BEGIN

   
   EXECUTE  IMMEDIATE 'TRUNCATE TABLE CAPRA_PAID_TXN_INTF_TRND';
   INSERT INTO CAPRA_PAID_TXN_INTF_TRND (
   SELECT   ape.paid_amt,ape.pmt_dt,EXTRACT(MONTH FROM ape.pmt_dt) pmt_month,  EXTRACT(YEAR FROM ape.pmt_dt) pmt_year,  ape.vdr_id,
            ape.vdr_loc,ape.vdr_nm,case when ape.interface_id='SIT' then 'BCH' else ape.interface_id end interface_id,ape.interface_nm
           ,ape.inv_dt,ape.dtp,ape.vdr_loc_pay_terms,ape.vdr_loc_pay_days,ape.erp,
           case when UPPER(ape.lob)='CORP' then 'CFS' else UPPER(ape.lob) end LOB,ape.vchr_loc_pay_terms,ape.vchr_loc_pay_days
           ,ape.business_unit,  ape.inv_no,  ape.vdr_set_id,  ape.pmt_meth,
            ape.vchr_id,  ape.clrg_doc_no,  ape.vchr_fisc_yr  
    FROM CAPRA_PAID_TXN ape
    WHERE (ape.vdr_acct_grp NOT IN ('ZVBE', 'ZVBI', 'ZICO', 'ZIAF', 'ZOFF') OR ape.vdr_acct_grp IS NULL) AND ape.rec_status != 0);
  
   -- Sum of paid_amt from capra_paid_txn
   EXECUTE IMMEDIATE 'TRUNCATE TABLE CAPRA_INTERFACE_TRND_PAID_AMT';
   INSERT INTO CAPRA_INTERFACE_TRND_PAID_AMT ( INTERFACE_ID, PMT_MONTH, PMT_YEAR, MONTHLY_PAID_AMT) --, INCLUDES_CREDITS )
    (SELECT vape.interface_id, vape.pmt_month, vape.pmt_year, SUM(vape.paid_amt)
    FROM CAPRA_PAID_TXN_INTF_TRND vape --WHERE VAPE.INTERFACE_ID IN ('3PP','13966')
    GROUP BY vape.interface_id, vape.pmt_month, vape.pmt_year);
   COMMIT;
   
   -- Sum of paid amounts that are greater than 0 from capra_paid_txn
    EXECUTE IMMEDIATE 'TRUNCATE TABLE CAPRA_INTERFACE_TRND_CRDT_AMT';
    INSERT INTO CAPRA_INTERFACE_TRND_CRDT_AMT ( INTERFACE_ID, PMT_MONTH, PMT_YEAR, MONTHLY_PAID_AMT) --, INCLUDES_CREDITS )
    (SELECT vape.interface_id, vape.pmt_month, vape.pmt_year, SUM(vape.paid_amt)
    FROM CAPRA_PAID_TXN_INTF_TRND vape
    WHERE vape.paid_amt > 0 --AND VAPE.INTERFACE_ID IN ('3PP','13966')
    GROUP BY vape.interface_id, vape.pmt_month, vape.pmt_year);
    COMMIT;
    
    -- Calculating WADTP values for all the transactions that have paid_amount > 0
    EXECUTE IMMEDIATE 'TRUNCATE TABLE CAPRA_INTERFACE_TRND_RPT_WADTP';
    INSERT INTO CAPRA_INTERFACE_TRND_RPT_WADTP ( INTERFACE_ID, PMT_MONTH, PMT_YEAR, WADTP )
     SELECT vape.interface_id, vape.pmt_month, vape.pmt_year, 
            ROUND(SUM((vape.paid_amt/mtp.MONTHLY_PAID_AMT)*(vape.DTP)), 2)
     FROM CAPRA_PAID_TXN_INTF_TRND vape, CAPRA_INTERFACE_TRND_CRDT_AMT mtp
     WHERE vape.paid_amt > 0
     AND vape.interface_id = mtp.interface_id
     AND vape.pmt_month = mtp.pmt_month --AND VAPE.INTERFACE_ID IN ('3PP','13966')
     AND vape.pmt_year = mtp.pmt_year
     GROUP BY vape.INTERFACE_ID, vape.pmt_month, vape.pmt_year;
     COMMIT;



   EXECUTE IMMEDIATE 'TRUNCATE TABLE CAPRA_AP_INTERFACE_TREND_REPORT';
   FOR I IN C_MAIN
   LOOP
        V_INTF_NM                    := NULL;
        V_SET_ID                    := NULL;
        V_WADT_AMT                  := 0;
        V_CURR_YR_PDAMT             := 0;
        V_PREV_YR_PDAMT             := 0;
        V_PREV_TO_PREV_YR_PDAMT     := 0;
       
        V_PERCENT_INCR_PREV_MONTH   := 0;
        V_PERCENT_INCR_JAN2015      := 0;
        V_PERCENT_INCR_JAN2016      := 0;
        V_DTP_VAL1                  := 0;
        V_DTP_VAL2                  := 0;
    
        V_JAN_2015_WADTP            := 0;
        V_FEB_2015_WADTP            := 0;
        V_MAR_2015_WADTP            := 0;
        V_APR_2015_WADTP            := 0;
        V_MAY_2015_WADTP            := 0;
        V_JUN_2015_WADTP            := 0;
        V_JUL_2015_WADTP            := 0;
        V_AUG_2015_WADTP            := 0;
        V_SEP_2015_WADTP            := 0;
        V_OCT_2015_WADTP            := 0;
        V_NOV_2015_WADTP            := 0;
        V_DEC_2015_WADTP            := 0;
    
        V_JAN_2016_WADTP            := 0;
        V_FEB_2016_WADTP            := 0;
        V_MAR_2016_WADTP            := 0;
        V_APR_2016_WADTP            := 0;
        V_MAY_2016_WADTP            := 0;
        V_JUN_2016_WADTP            := 0;
        V_JUL_2016_WADTP            := 0;
        V_AUG_2016_WADTP            := 0;
        V_SEP_2016_WADTP            := 0;
        V_OCT_2016_WADTP            := 0;
        V_NOV_2016_WADTP            := 0;
        V_DEC_2016_WADTP            := 0;
     
        V_JAN_2017_WADTP            := 0;
        V_FEB_2017_WADTP            := 0;
        V_MAR_2017_WADTP            := 0;
        V_APR_2017_WADTP            := 0;
        V_MAY_2017_WADTP            := 0;
        V_JUN_2017_WADTP            := 0;
        V_JUL_2017_WADTP            := 0;
        V_AUG_2017_WADTP            := 0;
        V_SEP_2017_WADTP            := 0;
        V_OCT_2017_WADTP            := 0;
        V_NOV_2017_WADTP            := 0;
        V_DEC_2017_WADTP            := 0;
     
    BEGIN    
          SELECT SUM(CR.MONTHLY_PAID_AMT) 
          INTO V_PREV_TO_PREV_YR_PDAMT
          FROM CAPRA_INTERFACE_TRND_PAID_AMT CR
          WHERE CR.INTERFACE_ID=I.INTERFACE_ID  AND CR.PMT_YEAR=V_PREV_TO_PREV_YEAR;
    EXCEPTION WHEN NO_DATA_FOUND 
    THEN
         V_PREV_TO_PREV_YR_PDAMT := 0;
    END;
    
    BEGIN
          SELECT SUM(CR.MONTHLY_PAID_AMT) 
          INTO V_PREV_YR_PDAMT
          FROM CAPRA_INTERFACE_TRND_PAID_AMT CR
          WHERE CR.INTERFACE_ID=I.INTERFACE_ID AND CR.PMT_YEAR=V_PREV_YEAR;
    EXCEPTION WHEN NO_DATA_FOUND 
    THEN
         V_PREV_YR_PDAMT := 0;
    END;
    
    BEGIN  
           SELECT NVL(ROUND(SUM(CR.MONTHLY_PAID_AMT),2),0)
          INTO V_CURR_YR_PDAMT
          FROM CAPRA_INTERFACE_TRND_PAID_AMT CR
          WHERE CR.INTERFACE_ID=I.INTERFACE_ID  AND CR.PMT_YEAR=V_CURRENT_YEAR;
    EXCEPTION WHEN NO_DATA_FOUND 
    THEN
         V_CURR_YR_PDAMT := 0;
    END;

        V_INTF_NM    := NULL;

    BEGIN
        SELECT DISTINCT VDR_SET_ID INTO V_SET_ID
        FROM CAPRA_PAID_TXN_INTF_TRND WHERE INTERFACE_ID=I.INTERFACE_ID;
    EXCEPTION WHEN NO_DATA_FOUND
    THEN
        V_SET_ID    := NULL;
    END;   
   
      V_DTP_VAL1  := CAPRA_CALC_WADTP_PER_MONTH(I.INTERFACE_ID,V_CURRENT_YEAR,V_CURRENT_MONTH-1);
      IF V_CURRENT_MONTH = 2 
      THEN
          V_DTP_VAL2  := CAPRA_CALC_WADTP_PER_MONTH(I.INTERFACE_ID,V_PREV_YEAR,'12');
      ELSE
          V_DTP_VAL2  := CAPRA_CALC_WADTP_PER_MONTH(I.INTERFACE_ID,V_CURRENT_YEAR,V_CURRENT_MONTH-2);
      END IF;
      
      IF  V_DTP_VAL2 > 0 
      THEN
          V_PERCENT_INCR_PREV_MONTH := ROUND( (((V_DTP_VAL1 - V_DTP_VAL2) * 100) / V_DTP_VAL2), 1);
      END IF;
    
      V_DTP_VAL2 := 0;
      V_DTP_VAL2  := CAPRA_CALC_WADTP_PER_MONTH(I.INTERFACE_ID,V_PREV_TO_PREV_YEAR,'1');
      IF  V_DTP_VAL2 > 0 
      THEN
          V_PERCENT_INCR_JAN2015 := ROUND( (((V_DTP_VAL1 - V_DTP_VAL2) * 100) / V_DTP_VAL2), 1);
      END IF;
    
      V_DTP_VAL2 := 0;
      V_DTP_VAL2  := CAPRA_CALC_WADTP_PER_MONTH(I.INTERFACE_ID,V_PREV_YEAR,'1');
      IF  V_DTP_VAL2 > 0 
      THEN
          V_PERCENT_INCR_JAN2016 := ROUND( (((V_DTP_VAL1 - V_DTP_VAL2) * 100) / V_DTP_VAL2), 1);
      END IF;
    
      
      V_JAN_2015_WADTP := CAPRA_CALC_WADTP_PER_MONTH(I.INTERFACE_ID,V_PREV_TO_PREV_YEAR,'1');
      V_FEB_2015_WADTP := CAPRA_CALC_WADTP_PER_MONTH(I.INTERFACE_ID,V_PREV_TO_PREV_YEAR,'2');
      V_MAR_2015_WADTP := CAPRA_CALC_WADTP_PER_MONTH(I.INTERFACE_ID,V_PREV_TO_PREV_YEAR,'3');
      V_APR_2015_WADTP := CAPRA_CALC_WADTP_PER_MONTH(I.INTERFACE_ID,V_PREV_TO_PREV_YEAR,'4');
      V_MAY_2015_WADTP := CAPRA_CALC_WADTP_PER_MONTH(I.INTERFACE_ID,V_PREV_TO_PREV_YEAR,'5');
      V_JUN_2015_WADTP := CAPRA_CALC_WADTP_PER_MONTH(I.INTERFACE_ID,V_PREV_TO_PREV_YEAR,'6');
      V_JUL_2015_WADTP := CAPRA_CALC_WADTP_PER_MONTH(I.INTERFACE_ID,V_PREV_TO_PREV_YEAR,'7');
      V_AUG_2015_WADTP := CAPRA_CALC_WADTP_PER_MONTH(I.INTERFACE_ID,V_PREV_TO_PREV_YEAR,'8');
      V_SEP_2015_WADTP := CAPRA_CALC_WADTP_PER_MONTH(I.INTERFACE_ID,V_PREV_TO_PREV_YEAR,'9');
      V_OCT_2015_WADTP := CAPRA_CALC_WADTP_PER_MONTH(I.INTERFACE_ID,V_PREV_TO_PREV_YEAR,'10');
      V_NOV_2015_WADTP := CAPRA_CALC_WADTP_PER_MONTH(I.INTERFACE_ID,V_PREV_TO_PREV_YEAR,'11');
      V_DEC_2015_WADTP := CAPRA_CALC_WADTP_PER_MONTH(I.INTERFACE_ID,V_PREV_TO_PREV_YEAR,'12');
      
      V_JAN_2016_WADTP := CAPRA_CALC_WADTP_PER_MONTH(I.INTERFACE_ID,V_PREV_YEAR,'1');
      V_FEB_2016_WADTP := CAPRA_CALC_WADTP_PER_MONTH(I.INTERFACE_ID,V_PREV_YEAR,'2');
      V_MAR_2016_WADTP := CAPRA_CALC_WADTP_PER_MONTH(I.INTERFACE_ID,V_PREV_YEAR,'3');
      V_APR_2016_WADTP := CAPRA_CALC_WADTP_PER_MONTH(I.INTERFACE_ID,V_PREV_YEAR,'4');
      V_MAY_2016_WADTP := CAPRA_CALC_WADTP_PER_MONTH(I.INTERFACE_ID,V_PREV_YEAR,'5');
      V_JUN_2016_WADTP := CAPRA_CALC_WADTP_PER_MONTH(I.INTERFACE_ID,V_PREV_YEAR,'6');
      V_JUL_2016_WADTP := CAPRA_CALC_WADTP_PER_MONTH(I.INTERFACE_ID,V_PREV_YEAR,'7');
      V_AUG_2016_WADTP := CAPRA_CALC_WADTP_PER_MONTH(I.INTERFACE_ID,V_PREV_YEAR,'8');
      V_SEP_2016_WADTP := CAPRA_CALC_WADTP_PER_MONTH(I.INTERFACE_ID,V_PREV_YEAR,'9');
      V_OCT_2016_WADTP := CAPRA_CALC_WADTP_PER_MONTH(I.INTERFACE_ID,V_PREV_YEAR,'10');
      V_NOV_2016_WADTP := CAPRA_CALC_WADTP_PER_MONTH(I.INTERFACE_ID,V_PREV_YEAR,'11');
      V_DEC_2016_WADTP := CAPRA_CALC_WADTP_PER_MONTH(I.INTERFACE_ID,V_PREV_YEAR,'12');
      
      V_JAN_2017_WADTP := CAPRA_CALC_WADTP_PER_MONTH(I.INTERFACE_ID,V_CURRENT_YEAR,'1');
      V_FEB_2017_WADTP := CAPRA_CALC_WADTP_PER_MONTH(I.INTERFACE_ID,V_CURRENT_YEAR,'2');
      V_MAR_2017_WADTP := CAPRA_CALC_WADTP_PER_MONTH(I.INTERFACE_ID,V_CURRENT_YEAR,'3');
      V_APR_2017_WADTP := CAPRA_CALC_WADTP_PER_MONTH(I.INTERFACE_ID,V_CURRENT_YEAR,'4');
      V_MAY_2017_WADTP := CAPRA_CALC_WADTP_PER_MONTH(I.INTERFACE_ID,V_CURRENT_YEAR,'5');
      V_JUN_2017_WADTP := CAPRA_CALC_WADTP_PER_MONTH(I.INTERFACE_ID,V_CURRENT_YEAR,'6');
      V_JUL_2017_WADTP := CAPRA_CALC_WADTP_PER_MONTH(I.INTERFACE_ID,V_CURRENT_YEAR,'7');
      V_AUG_2017_WADTP := CAPRA_CALC_WADTP_PER_MONTH(I.INTERFACE_ID,V_CURRENT_YEAR,'8');
      V_SEP_2017_WADTP := CAPRA_CALC_WADTP_PER_MONTH(I.INTERFACE_ID,V_CURRENT_YEAR,'9');
      V_OCT_2017_WADTP := CAPRA_CALC_WADTP_PER_MONTH(I.INTERFACE_ID,V_CURRENT_YEAR,'10');
      V_NOV_2017_WADTP := CAPRA_CALC_WADTP_PER_MONTH(I.INTERFACE_ID,V_CURRENT_YEAR,'11');
      V_DEC_2017_WADTP := CAPRA_CALC_WADTP_PER_MONTH(I.INTERFACE_ID,V_CURRENT_YEAR,'12');
      
     INSERT INTO CAPRA_INTERFACE_TREND_REPORT 
     VALUES (I.INTERFACE_ID,(SELECT DISTINCT INTERFACE_NM FROM CAPRA_PAID_TXN_INTF_TRND WHERE INTERFACE_ID=I.INTERFACE_ID AND ROWNUM=1)
     ,V_SET_ID,V_PREV_YR_PDAMT,V_CURR_YR_PDAMT,V_JAN_2015_WADTP,V_FEB_2015_WADTP,V_MAR_2015_WADTP,V_APR_2015_WADTP,V_MAY_2015_WADTP
     ,V_JUN_2015_WADTP,V_JUL_2015_WADTP,V_AUG_2015_WADTP,V_SEP_2015_WADTP,V_OCT_2015_WADTP,V_NOV_2015_WADTP,V_DEC_2015_WADTP
     ,V_JAN_2016_WADTP,V_FEB_2016_WADTP,V_MAR_2016_WADTP,V_APR_2016_WADTP,V_MAY_2016_WADTP,V_JUN_2016_WADTP
     ,V_JUL_2016_WADTP,V_AUG_2016_WADTP,V_SEP_2016_WADTP,V_OCT_2016_WADTP,V_NOV_2016_WADTP,V_DEC_2016_WADTP,V_PERCENT_INCR_PREV_MONTH
     ,V_PERCENT_INCR_JAN2015,V_JAN_2017_WADTP,V_FEB_2017_WADTP,V_MAR_2017_WADTP,V_APR_2017_WADTP,V_MAY_2017_WADTP,V_JUN_2017_WADTP
     ,V_JUL_2017_WADTP,V_AUG_2017_WADTP,V_SEP_2017_WADTP,V_OCT_2017_WADTP,V_NOV_2017_WADTP,V_DEC_2017_WADTP
     ,V_PREV_TO_PREV_YR_PDAMT,V_PERCENT_INCR_JAN2016);

END LOOP;

--
   INSERT INTO TEMP_UPD2 VALUES(SYSTIMESTAMP,'STEP2',1);
   COMMIT;
--   
EXCEPTION
WHEN OTHERS THEN
   raise_application_error(-20001,'CAPRA_LKP_INT_TRND_RPT - '||SQLCODE||' -ERROR- '||SQLERRM);
 
   
END CAPRA_LKP_INT_TRND_RPT;